### ISSUE TITLE
Problem with create census api endpoint

### ISSUE THREAD

**Issue by javheroli** [EGC-Decide/locaste#106]
The api document specifies that api endpoint to create a census object need inputs (voting_id and voter_id)  but It doesn't work properly, I get a 500 http status.
Remplacing voter_id to an array voter: [] seems to work

**Comment by carjimcor** [comment]
As @jualinfer pointed me out, the Create method of the api was only supporting a parameter "voters" instead of "voter_id" before we forked the EGC/decide repository. So it's not actually a bug we introduced as I thought.

I can think of two possible solutions:
1. Fix the parameters that appear in the api for the create method of census.
2. Or, add the possibility of using "voter_id" to the current implementation.

**Comment by javheroli** [comment]
Solution 1 is fine for me, I consumed the endpoint using "voters" parameter and works perfectly
